# Generated by Django 4.2.7 on 2023-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('added_dt', models.DateTimeField()),
            ],
        ),
    ]
