# Generated by Django 4.2.7 on 2023-11-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_added_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('updated_dt', models.DateTimeField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.question')),
            ],
        ),
    ]
